# esp32-S3-ws4-caravan v1.0
"""Generates font_latin1.c: the Latin-1 letters (and the euro sign, OE ligature)
missing from LVGL's built-in Montserrat fonts, rendered from Montserrat-Medium.ttf
(the TTF LVGL's built-ins come from), one font per built-in size. Each falls back
to the built-in font of the same size for everything else, so it can be used in
its place. Covers Swedish, Danish, Norwegian, Finnish, German, Dutch, French,
Spanish, Italian, Portuguese and Icelandic.
Usage: python3 gen_font_latin1.py Montserrat-Medium.ttf font_latin1.c"""
import sys
from PIL import ImageFont
TTF, OUT = sys.argv[1], sys.argv[2]
# U+00A1..U+00FF without the soft hyphen and the degree sign (built in), plus OE oe and euro
CHARS = "".join(chr(c) for c in range(0xA1, 0x100) if c not in (0xAD, 0xB0)) + "\u0152\u0153\u20ac"
SIZES = {14: (16, 3), 16: (18, 3), 20: (22, 4), 28: (30, 5), 32: (35, 6), 48: (52, 9)}  # built-in line_height, base_line

out = ["/* font_latin1: the Latin-1 letters LVGL's built-in Montserrat fonts lack",
       " * (U+00A1-U+00FF, OE, oe, euro), rendered from Montserrat Medium, 4 bpp.",
       " * Each font falls back to the built-in Montserrat of the same size, and has a",
       " * slightly taller line so accents and the ring on the A are not clipped.",
       " * Used only when a translation is active. Generated by tools/gen_font_latin1.py. */",
       "#include <lvgl.h>", ""]
codes = sorted(ord(c) for c in CHARS)
for size, (lh, base) in SIZES.items():
    f = ImageFont.truetype(TTF, size)
    bitmap, dsc, top, bottom = [], [], lh - base, base
    for cp in codes:
        ch = chr(cp)
        mask, (ox, oy) = f.getmask2(ch, mode="L", anchor="ls")
        w, h = mask.size
        px = [round(mask.getpixel((x, y)) * 15 / 255) for y in range(h) for x in range(w)]
        if len(px) % 2: px.append(0)
        idx = len(bitmap)
        bitmap += [(px[i] << 4) | px[i + 1] for i in range(0, len(px), 2)]
        ofs_y = -(oy + h)
        top = max(top, -oy)
        pass  # below the baseline: kept at the built-in depth (only a cedilla tail can reach a pixel lower)
        dsc.append((idx, round(f.getlength(ch) * 16), w, h, ox, ofs_y, "U+%04X" % cp))
    lh2 = top + bottom
    n = f"font_latin1_{size}"
    out.append(f"#if LV_FONT_MONTSERRAT_{size}")
    out.append(f"static LV_ATTRIBUTE_LARGE_CONST const uint8_t {n}_bitmap[] = {{")
    for i in range(0, len(bitmap), 16):
        out.append("    " + ", ".join(f"0x{b:02x}" for b in bitmap[i:i + 16]) + ",")
    out.append("};")
    out.append(f"static const lv_font_fmt_txt_glyph_dsc_t {n}_glyphs[] = {{")
    out.append("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},")
    for (i, a, w, h, ox, oy, ch) in dsc:
        out.append(f"    {{.bitmap_index = {i}, .adv_w = {a}, .box_w = {w}, .box_h = {h}, .ofs_x = {ox}, .ofs_y = {oy}}}, /* {ch} */")
    out.append("};")
    first = codes[0]
    out.append(f"static const uint16_t {n}_list[] = {{" + ", ".join(str(c - first) for c in codes) + "};")
    out.append(f"static const lv_font_fmt_txt_cmap_t {n}_cmaps[] = {{")
    out.append(f"    {{.range_start = {first}, .range_length = {codes[-1] - first + 1}, .glyph_id_start = 1,")
    out.append(f"     .unicode_list = {n}_list, .glyph_id_ofs_list = NULL, .list_length = {len(codes)}, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}}")
    out.append("};")
    out.append(f"static lv_font_fmt_txt_glyph_cache_t {n}_cache;")
    out.append(f"static const lv_font_fmt_txt_dsc_t {n}_dsc = {{")
    out.append(f"    .glyph_bitmap = {n}_bitmap, .glyph_dsc = {n}_glyphs, .cmaps = {n}_cmaps, .kern_dsc = NULL,")
    out.append(f"    .kern_scale = 0, .cmap_num = 1, .bpp = 4, .kern_classes = 0, .bitmap_format = 0, .cache = &{n}_cache")
    out.append("};")
    out.append(f"const lv_font_t {n} = {{")
    out.append("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    out.append("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    out.append(f"    .line_height = {lh2},")
    out.append(f"    .base_line = {bottom},")
    out.append("    .subpx = LV_FONT_SUBPX_NONE,")
    out.append(f"    .underline_position = {-max(1, size // 14)},")
    out.append(f"    .underline_thickness = {max(1, size // 14)},")
    out.append(f"    .dsc = &{n}_dsc,")
    out.append(f"    .fallback = &lv_font_montserrat_{size},")
    out.append("};")
    out.append("#endif")
    out.append("")
    print(n, "line", lh, "->", lh2, "bytes", len(bitmap))
open(OUT, "w").write("\n".join(out))
